### ISSUE TITLE
Systems Diagram: Due Sep 30th

### ISSUE THREAD

**Issue by JJwilkin** [pharma-box/docs#16]
## Description
We have to create a systems diagram to describe our problem space for our meeting with the two profs.

## References and Links
*should add previous course documents on how to make a systems diagram*

**Comment by SammyRobensParadise** [comment]
@rajwanialiya I think we should pair on this. I am thinking we create one of those sink/source/faucet diagrams that we used the last term to explain this. i think it will be a good way of explaining the problem we are trying to solve in terms of optimization

**Comment by SammyRobensParadise** [comment]
This will be a system diagram using a sink/source/faucet approach.

**Comment by SammyRobensParadise** [comment]
@SammyRobensParadise  will do patient flow, and @rajwanialiya will do the pharmacists flow
https://www.figma.com/file/uPjMeCcjFEEKMRmTdZLShl/System-Diagram?node-id=0%3A1

**Comment by SammyRobensParadise** [comment]
Peep the preliminary systems diagram @rajwanialiya 
<img width="3613" alt="System Diagram" src="https://user-images.githubusercontent.com/33642354/193114496-d04915aa-dc52-45f6-b704-dbffd2473c2f.png">

**Comment by SammyRobensParadise** [comment]
We need to add the effects and stuff, I am curious about the structure, and what you think of it. Am I missing anything @rajwanialiya

**Comment by SammyRobensParadise** [comment]
Closing this as we have a systems diagram now available here
https://www.figma.com/file/uPjMeCcjFEEKMRmTdZLShl/System-Diagram?node-id=0%3A1
