### ISSUE TITLE
Meet With RR + MB Meet with Teams: Sep 30th 10:20-10:40 AM

### ISSUE THREAD

**Issue by JJwilkin** [pharma-box/docs#17]
## Description
We'll have a meeting on Friday Sep 30 at 10:20-10:40 AM with Prof. Roufail and Prof. Borland as an introductory and guidance meeting to ensure we're on the right path.

## Subtasks

- [x] #16 
- [x] #19
- [x] #20
- [x] #21

## Blockers
List any blocking tasks or requirements

## Is this task part of a graded deliverable?
Yes

## References and Links

 https://learn.uwaterloo.ca/d2l/le/content/841590/viewContent/4507290/View

**Comment by SammyRobensParadise** [comment]
Closing this as all subtasks are complete. Please re-open if there are any issues @rajwanialiya @JJwilkin @hnagri52
