### ISSUE TITLE
Brainstorm questions for MB + RR for meeting: Due Sep 30th

### ISSUE THREAD

**Issue by JJwilkin** [pharma-box/docs#21]
## Description
We want to use our meeting with Prof.Borland and Prof Roufail to ask any important questions or for general guidance/advice.

Potential useful questions:
- Advice they observed from similar projects in the past?
- What are some potential obstacles you initially see with our approach and problem space?

**Comment by SammyRobensParadise** [comment]
I think this would be good to tackle at our Wednesday meeting on September 28th

**Comment by SammyRobensParadise** [comment]
Closing this, since. we had our meeting and it went pretty ✅
