### ISSUE TITLE
Create 2 primary user personas

### ISSUE THREAD

**Issue by hnagri52** [pharma-box/docs#44]
General terms,
the primary user, in this case, will be the pharmacists, and the secondary user will be the retail pharmacy owner

**Comment by SammyRobensParadise** [comment]
I realized we already have a secondary user persona so this issue is going to be to create two primary user personas

**Comment by SammyRobensParadise** [comment]
Here are the two user personas
[PERSONA - Camila Nadal.pdf](https://github.com/pharma-box/docs/files/9718406/PERSONA.-.Camila.Nadal.pdf)
![PERSONA - Camila Nadal](https://user-images.githubusercontent.com/33642354/194145385-300c4203-3eed-4014-99bc-6a5cd9edf6c2.png)
[PERSONA - Aaron Motz.pdf](https://github.com/pharma-box/docs/files/9718409/PERSONA.-.Aaron.Motz.pdf)
![PERSONA - Aaron Motz](https://user-images.githubusercontent.com/33642354/194145407-a36782f4-435a-4bf9-96ef-b7e7a1a69954.png)
