### ISSUE TITLE
Create user surveys targeting primary users

### ISSUE THREAD

**Issue by hnagri52** [pharma-box/docs#46]
## Details
We are going to do this first, before we do #52 and #51 so that we can better target our users with questions.

## How are going to do this
Create a google form with likert-scale style questions. The survey should take no more than three minutes to take
We should figure out a way to track where users are reaching the survey from

We need two surveys, one for patients and one for pharmacists. we shouldn't have any issues finding patients, when it comes to finding pharmacists, we should reach out to our advisor, and look at pharmacy subreddits.

**Comment by SammyRobensParadise** [comment]
https://docs.google.com/document/d/1GAujtzwMpTBW51YhI7zmsCiPwb2uGLydpv9fkZE39og/edit#

**Comment by SammyRobensParadise** [comment]
is this issue `closed`?

**Comment by SammyRobensParadise** [comment]
closing this as I believe we have created the questionnaire
