### ISSUE TITLE
post user surveys targeting primary users

### ISSUE THREAD

**Issue by hnagri52** [pharma-box/docs#47]
due date: tuesday september 27

**Comment by SammyRobensParadise** [comment]
Updated due date: September 30th

**Comment by SammyRobensParadise** [comment]
@rajwanialiya can this be closed? I am not sure there was a clear definition of done. I think we need to talk about what "post" means. Do we need to make a  social media post? as well?

**Comment by rajwanialiya** [comment]
Yes I'll close it. Post in this context means hang the survey posters up.
