### ISSUE TITLE
Add last week meeting minutes to github 

### ISSUE THREAD

**Issue by hnagri52** [pharma-box/docs#54]
## Description
Describe the task in a few sentences

hey!! Just creating an issue for last week's meeting minutes! Please close when they are added 

## Subtasks
List subtasks if applicable

## Blockers
List any blocking tasks or requirements

## Is this task part of a graded deliverable?
(Yes/No)

## Does this task require more clarity to be actionable?
(Yes/No)

## Requirements to close task/issue
- [ ] requirement 1
- [ ] requirement 2
- [ ] requirement 3

## References and Links
link any supporting documentation, google docs, code, etc.

- [ ] I have added the appropriate labels to this task

**Comment by SammyRobensParadise** [comment]
@hnagri52 is this done and can it be closed?

**Comment by hnagri52** [comment]
> @hnagri52 is this done and can it be closed?

@JJwilkin

**Comment by SammyRobensParadise** [comment]
bump @JJwilkin

**Comment by SammyRobensParadise** [comment]
bump @JJwilkin

**Comment by SammyRobensParadise** [comment]
closing this then
