### ISSUE TITLE
Low Fidelity Prototype: Due Oct 21 2022

### ISSUE THREAD

**Issue by SammyRobensParadise** [pharma-box/docs#66]
# LFP Development

This is the `epic-style` issue that will encompass the development of the LFP. It will be assigned to all team members and tasks will be added as subtasks to this epic as needed.

we need to answer a couple of questions. What do we want to discover from our LFP? structuring our LFP around that super basic problem we want to solve will help us develop the LFP in a short amount of time

**Comment by hnagri52** [comment]
@SammyRobensParadise @JJwilkin @rajwanialiya 

Do you guys think we're on pace to meet this goal? I find it might be difficult to build out a LFP in a bit over a week, what do you guys think?

**Comment by SammyRobensParadise** [comment]
> @SammyRobensParadise @JJwilkin @rajwanialiya
> 
> Do you guys think we're on pace to meet this goal? I find it might be difficult to build out a LFP in a bit over a week, what do you guys think?

We can push this back
